[2021-10-19 16:32:32 +0000] [33671] [INFO] Starting gunicorn 20.1.0
[2021-10-19 16:32:32 +0000] [33671] [INFO] Listening at: http://10.214.29.110:5088 (33671)
[2021-10-19 16:32:32 +0000] [33671] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2021-10-19 16:32:32 +0000] [33672] [INFO] Booting worker with pid: 33672
[2021-10-19 16:32:32 +0000] [33673] [INFO] Booting worker with pid: 33673
[2021-10-19 16:32:32 +0000] [33674] [INFO] Booting worker with pid: 33674
[2021-10-19 16:32:32 +0000] [33672] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/disk1/jzj/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/nfs/jzj/ASM_SHOW/run.py", line 1, in <module>
    from app import app
  File "/nfs/jzj/ASM_SHOW/app/__init__.py", line 9, in <module>
    app.config.from_object('config')
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/werkzeug/utils.py", line 865, in import_string
    __import__(import_name)
  File "/nfs/jzj/ASM_SHOW/config.py", line 27, in <module>
    'model': asm.net.deeplab.modeling.deeplabv3_resnet50,
NameError: name 'asm' is not defined
[2021-10-19 16:32:32 +0000] [33674] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/disk1/jzj/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/nfs/jzj/ASM_SHOW/run.py", line 1, in <module>
    from app import app
  File "/nfs/jzj/ASM_SHOW/app/__init__.py", line 9, in <module>
    app.config.from_object('config')
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/werkzeug/utils.py", line 865, in import_string
    __import__(import_name)
  File "/nfs/jzj/ASM_SHOW/config.py", line 27, in <module>
    'model': asm.net.deeplab.modeling.deeplabv3_resnet50,
NameError: name 'asm' is not defined
[2021-10-19 16:32:32 +0000] [33673] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/disk1/jzj/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/nfs/jzj/ASM_SHOW/run.py", line 1, in <module>
    from app import app
  File "/nfs/jzj/ASM_SHOW/app/__init__.py", line 9, in <module>
    app.config.from_object('config')
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/werkzeug/utils.py", line 865, in import_string
    __import__(import_name)
  File "/nfs/jzj/ASM_SHOW/config.py", line 27, in <module>
    'model': asm.net.deeplab.modeling.deeplabv3_resnet50,
NameError: name 'asm' is not defined
[2021-10-19 16:32:32 +0000] [33672] [INFO] Worker exiting (pid: 33672)
[2021-10-19 16:32:32 +0000] [33674] [INFO] Worker exiting (pid: 33674)
[2021-10-19 16:32:32 +0000] [33673] [INFO] Worker exiting (pid: 33673)
[2021-10-19 16:33:10 +0000] [34069] [INFO] Starting gunicorn 20.1.0
[2021-10-19 16:33:10 +0000] [34069] [INFO] Listening at: http://10.214.29.110:5088 (34069)
[2021-10-19 16:33:10 +0000] [34069] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2021-10-19 16:33:10 +0000] [34070] [INFO] Booting worker with pid: 34070
[2021-10-19 16:33:10 +0000] [34071] [INFO] Booting worker with pid: 34071
[2021-10-19 16:33:10 +0000] [34072] [INFO] Booting worker with pid: 34072
[2021-10-19 16:33:10 +0000] [34070] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/disk1/jzj/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/nfs/jzj/ASM_SHOW/run.py", line 1, in <module>
    from app import app
  File "/nfs/jzj/ASM_SHOW/app/__init__.py", line 9, in <module>
    app.config.from_object('config')
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/werkzeug/utils.py", line 865, in import_string
    __import__(import_name)
  File "/nfs/jzj/ASM_SHOW/config.py", line 27, in <module>
    'model': asm.net.deeplab.modeling.deeplabv3_resnet50,
NameError: name 'asm' is not defined
[2021-10-19 16:33:10 +0000] [34070] [INFO] Worker exiting (pid: 34070)
[2021-10-19 16:33:10 +0000] [34071] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/disk1/jzj/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/nfs/jzj/ASM_SHOW/run.py", line 1, in <module>
    from app import app
  File "/nfs/jzj/ASM_SHOW/app/__init__.py", line 9, in <module>
    app.config.from_object('config')
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/werkzeug/utils.py", line 865, in import_string
    __import__(import_name)
  File "/nfs/jzj/ASM_SHOW/config.py", line 27, in <module>
    'model': asm.net.deeplab.modeling.deeplabv3_resnet50,
NameError: name 'asm' is not defined
[2021-10-19 16:33:10 +0000] [34071] [INFO] Worker exiting (pid: 34071)
[2021-10-19 16:33:10 +0000] [34072] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/disk1/jzj/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/nfs/jzj/ASM_SHOW/run.py", line 1, in <module>
    from app import app
  File "/nfs/jzj/ASM_SHOW/app/__init__.py", line 9, in <module>
    app.config.from_object('config')
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/disk1/jzj/miniconda3/lib/python3.9/site-packages/werkzeug/utils.py", line 865, in import_string
    __import__(import_name)
  File "/nfs/jzj/ASM_SHOW/config.py", line 27, in <module>
    'model': asm.net.deeplab.modeling.deeplabv3_resnet50,
NameError: name 'asm' is not defined
[2021-10-19 16:33:10 +0000] [34072] [INFO] Worker exiting (pid: 34072)
[2021-10-19 16:33:10 +0000] [34069] [WARNING] Worker with pid 34072 was terminated due to signal 15
[2021-10-19 16:33:10 +0000] [34069] [WARNING] Worker with pid 34071 was terminated due to signal 15
[2021-10-19 16:33:10 +0000] [34069] [INFO] Shutting down: Master
[2021-10-19 16:33:10 +0000] [34069] [INFO] Reason: Worker failed to boot.
